# Example workflow for running notebook CI on pull requests
# Copy this file to your repository's .github/workflows/ directory

name: Notebook CI - Pull Request

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'notebooks/**'
      - '*.yml'
      - '*.yaml'
      - 'requirements.txt'
      - 'pyproject.toml'

jobs:
  validate-notebooks:
    uses: mgough-970/dev-actions/.github/workflows/notebook-ci-unified.yml@dev-actions-v2
    with:
      execution-mode: 'pr'
      python-version: "3.11"
      enable-validation: true
      enable-security: true
      enable-execution: true
      enable-storage: true
      enable-html-build: false
    secrets:
      CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}
      CASJOBS_PW: ${{ secrets.CASJOBS_PW }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
