# Notebook CI/CD workflow with custom runners for jwst-validation-notebooks
# Copy this file to your repository's .github/workflows/ directory

name: >
  Notebook CI - JWST Validation
  ${{ github.event_name == 'workflow_dispatch' && format('[{0}]', inputs.execution_mode) || 
      github.event_name == 'pull_request' && '[PR]' ||
      github.event_name == 'push' && '[Main]' ||
      github.event_name == 'schedule' && '[Scheduled]' || '' }}

on:
  # Run on pull requests to main branch
  pull_request:
    branches: [ main ]
    paths:
      - 'notebooks/**'
      - 'requirements.txt'
      - 'ci_config.txt'
      - '.github/workflows/**'

  # Run on pushes to main branch
  push:
    branches: [ main ]
    paths:
      - 'notebooks/**'
      - 'requirements.txt'
      - 'ci_config.txt'

  # Run on schedule (weekly on Sundays at 2 AM UTC)
  schedule:
    - cron: '0 2 * * 0'

  # Allow manual triggering
  workflow_dispatch:
    inputs:
      execution_mode:
        description: 'Execution mode'
        required: false
        default: 'cache_only'
        type: choice
        options:
          - cache_only
          - force_execute
          - collect_only
      notebook_pattern:
        description: 'Notebook pattern (optional)'
        required: false
        default: ''
        type: string

jobs:
  notebook-ci:
    uses: spacetelescope/notebook-ci-actions/.github/workflows/notebook-ci-unified.yml@dev-actions-v2-pipeline
    with:
      # Repository-specific configuration
      notebook_path: 'notebooks'
      python_version: '3.11'
      
      # Execution settings
      execution_mode: ${{ inputs.execution_mode || (github.event_name == 'pull_request' && 'cache_only' || 'force_execute') }}
      notebook_pattern: ${{ inputs.notebook_pattern || '' }}
      
      # Environment settings
      environment_file: 'requirements.txt'
      conda_environment_file: ''
      
      # Security and validation
      security_check: true
      notebook_validation: true
      
      # Documentation generation (enable for main branch)
      generate_docs: ${{ github.ref == 'refs/heads/main' }}
      docs_artifact: 'jwst-validation-docs'
      
      # Custom Runner Configuration - NEW FEATURE
      custom-runner-config: true
      
      # Artifact settings
      artifact_retention_days: 30
      
      # Performance settings
      timeout_minutes: 120  # Increased for heavy JWST processing
      max_parallel: 2       # Reduced to avoid overwhelming custom runners
      
    secrets: inherit
