## This workflow performs PEP8 style checks on the python code in python scrips.
## This workflow scans all python scripts in a repository, not just those modified in a pull request.
name: PEP8 Script Style Check Execution

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
jobs:
  gather-scripts:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v5
      - id: set-matrix
        run: echo "matrix=$(find notebooks -name "*.py" | jq -cnR '[inputs | select(length>0)]')" >> $GITHUB_OUTPUT
  script-style-checks:
    needs: gather-scripts
    environment: ci_env
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            scripts: ${{ fromJson(needs.gather-scripts.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5 ## needed for caching
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          pip install flake8
          pip install numpy
          pip install pytz
      - name: Check-out notebook-ci-actions repository
        uses: actions/checkout@v5
        with:
          repository: spacetelescope/notebook-ci-actions
          path: temp_pep8checker
          ref: v3
      - name: Run PEP8 style check
        run: |
          python temp_pep8checker/.github/helpers/pep8_script_style_checker.py ${{ matrix.scripts }}
