name: Build JupyterBook and Deploy

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11"
      post-run-script:
        required: false
        type: string
        description: "Path to a post-processing script to run after building HTML (e.g., 'jdaviz_image_replacement.sh')"
    secrets:
      github-token:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up uv
      uses: astral-sh/setup-uv@v6.0.1
      with:
        version: "0.7.3"
        python-version: ${{ inputs.python-version }}
        enable-cache: true

    - name: Install JupyterBook
      run: |
        uv run pip install jupyter-book

    - name: Build JupyterBook
      run: |
        uv run jupyter-book build .

    - name: Run Post-Processing Script
      if: inputs.post-run-script != ''
      run: |
        if [ -f "${{ inputs.post-run-script }}" ]; then
          echo "Running post-processing script: ${{ inputs.post-run-script }}"
          chmod +x "${{ inputs.post-run-script }}"
          ./${{ inputs.post-run-script }}
        else
          echo "Warning: Post-processing script '${{ inputs.post-run-script }}' not found"
          exit 1
        fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.github-token }}
        publish_dir: _build/html
