name: Full Notebook CI Pipeline

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      execution-mode:
        required: true
        type: string
      single-filename:
        required: false
        type: string
      build-html:
        required: false
        type: boolean
        default: true
      security-scan:
        required: false
        type: boolean
        default: true

    secrets:
      CASJOBS_USERID:
        required: false
      CASJOBS_PW:
        required: false

jobs:
  validate-and-execute:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        notebook: []
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up uv
      uses: astral-sh/setup-uv@v6.0.1
      with:
        version: "0.7.3"
        python-version: ${{ inputs.python-version }}
        enable-cache: true

    - name: Set up micromamba for HST environment
      if: ${{ github.repository == 'spacetelescope/hst_notebooks' }}
      uses: mamba-org/setup-micromamba@v2.0.4
      with:
        init-shell: bash
        create-args: >-
          python=${{ inputs.python-version }}
          hstcal

    - name: Set up micromamba for standard environment
      if: ${{ github.repository != 'spacetelescope/hst_notebooks' }}
      uses: mamba-org/setup-micromamba@v2.0.4
      with:
        init-shell: bash
        create-args: >-
          python=${{ inputs.python-version }}

    - name: Detect docs-only changes
      id: detect_docs_only
      if: github.event_name == 'pull_request'
      run: |
        # Get list of changed files in the PR
        git fetch origin ${{ github.event.pull_request.base.ref }}
        CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD)
        echo "Changed files: $CHANGED_FILES"
        DOCS_ONLY=true
        for file in $CHANGED_FILES; do
          case "$file" in
            *.md|*.yml|*.yaml|*.html|*.css|*.js|_config.yml|_toc.yml)
              # docs/static/config files, allow
              ;;
            *)
              # Any other file disables docs-only mode
              DOCS_ONLY=false
              break
              ;;
          esac
        done
        echo "DOCS_ONLY=$DOCS_ONLY" >> $GITHUB_ENV
        echo "docs-only=$DOCS_ONLY" >> $GITHUB_OUTPUT

    - name: Install Validation Dependencies
      if: env.DOCS_ONLY != 'true'
      run: |
        uv pip install jupyter nbval nbconvert bandit

    - name: Validate Notebook
      if: env.DOCS_ONLY != 'true'
      run: |
        if [[ "${{ inputs.single-filename }}" != "" ]]; then
          uv run pytest --nbval --nbval-cell-timeout=4000 "${{ inputs.single-filename }}"
        else
          find notebooks/ -name '*.ipynb' | while read nb; do
            uv run pytest --nbval --nbval-cell-timeout=4000 "$nb"
          done
        fi

    - name: Execute Notebook
      if: env.DOCS_ONLY != 'true'
      run: |
        if [[ "${{ inputs.single-filename }}" != "" ]]; then
          uv run jupyter nbconvert --to notebook --execute --inplace "${{ inputs.single-filename }}"
        else
          find notebooks/ -name '*.ipynb' | while read nb; do
            uv run jupyter nbconvert --to notebook --execute --inplace "$nb"
          done
        fi

    - name: Security Scan
      if: env.DOCS_ONLY != 'true' && inputs.security-scan == true
      run: |
        find notebooks/ -name '*.ipynb' | while read nb; do
          uv run jupyter nbconvert --to script "$nb"
        done
        uv run bandit -r notebooks/

    - name: Upload Notebook Artifacts if Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: failed-notebooks
        path: notebooks/

