name: Notebook Security Scan
on:
  workflow_call:
  
jobs:
  gather-notebooks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(find notebooks -name "*.ipynb" | jq -cnR '[inputs | select(length>0)]')" >> $GITHUB_OUTPUT
  BanditTests:
    needs: gather-notebooks
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            notebooks: ${{ fromJson(needs.gather-notebooks.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - name: Install dependencies
        run: |
          pip install bandit
          pip install nbconvert
          
      - name: Scan with Bandit
        run: |
          jupyter nbconvert --to script ${{ matrix.notebooks }}
          bandit ${{ matrix.notebooks }}

  NBDefenseTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          
      - name: Scan with NBDefense
        run: |
          pip install nbdefense
          python -m spacy download en_core_web_trf
          nbdefense scan -r notebooks/
      - name: Archive NBDefense Log
        uses: actions/upload-artifact@v4
        with:
          name: securityLog
          path: nbdefense*.html
          
          
