name: Count Tagged Issues

on:
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  count-issues-prescan:
    runs-on: ubuntu-latest
    outputs:
      issue_count: ${{ steps.issue-count.outputs.count }}
    env:
      GH_TOKEN: ${{ secrets.A11Y_TOKEN }} # Required to authenticate the GitHub CLI
      TARGET_LABEL: "axe-scanning-issue" # Change this to your specific tag

    steps:
      - name: Fetch and count open issues
        id: issue-count
        run: |
          # Fetch open issues with the label and get the count using jq length
          # COUNT=$(gh issue list --label "$TARGET_LABEL" --state open --json number | jq '. | length')
          COUNT=$(gh issue list --repo "${{ github.repository }}" --label "$TARGET_LABEL" --state open --json number | jq '. | length')
          
          echo "Found $COUNT open issues with the label '$TARGET_LABEL'."
          
          # Save the count to output so other steps can use it
          echo "count=$COUNT" >> $GITHUB_OUTPUT
      - name:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: This is where the scan goes
        id: issue-count
        run: |
          echo "SCAN GOES HERE!"